// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6SKC9feHv0pNY___HR9qRsz-WwpMaraA',
    appId: '1:763073770103:web:747d5649b588634654cc72',
    messagingSenderId: '763073770103',
    projectId: 'mimarketplace-c91b3',
    authDomain: 'mimarketplace-c91b3.firebaseapp.com',
    storageBucket: 'mimarketplace-c91b3.firebasestorage.app',
    measurementId: 'G-795Y5ZZJGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBhxcVtdAeZ0rORtju6pavz4jQblhj8tU',
    appId: '1:763073770103:android:78764195a0b07b0854cc72',
    messagingSenderId: '763073770103',
    projectId: 'mimarketplace-c91b3',
    storageBucket: 'mimarketplace-c91b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5MLE_78qGr7n-dSzBke-JgPZiENhtKJY',
    appId: '1:763073770103:ios:7aca8c8c17c9dd2c54cc72',
    messagingSenderId: '763073770103',
    projectId: 'mimarketplace-c91b3',
    storageBucket: 'mimarketplace-c91b3.firebasestorage.app',
    androidClientId: '763073770103-r59b5o374gam7u8lk7u762aolrbtd2qt.apps.googleusercontent.com',
    iosClientId: '763073770103-va2jerhrq9gnj7sj317gr3hmp49rvtp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mimarketplace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5MLE_78qGr7n-dSzBke-JgPZiENhtKJY',
    appId: '1:763073770103:ios:7aca8c8c17c9dd2c54cc72',
    messagingSenderId: '763073770103',
    projectId: 'mimarketplace-c91b3',
    storageBucket: 'mimarketplace-c91b3.firebasestorage.app',
    androidClientId: '763073770103-r59b5o374gam7u8lk7u762aolrbtd2qt.apps.googleusercontent.com',
    iosClientId: '763073770103-va2jerhrq9gnj7sj317gr3hmp49rvtp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.mimarketplace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6SKC9feHv0pNY___HR9qRsz-WwpMaraA',
    appId: '1:763073770103:web:dd75fe0f9a88656f54cc72',
    messagingSenderId: '763073770103',
    projectId: 'mimarketplace-c91b3',
    authDomain: 'mimarketplace-c91b3.firebaseapp.com',
    storageBucket: 'mimarketplace-c91b3.firebasestorage.app',
    measurementId: 'G-P7KPQRZ8HJ',
  );
}
